### ISSUE TITLE
导出的jar包没有directory entries 信息

### ISSUE THREAD

**Issue by hongdaorongThink** [zhyhang/export-jar#1]
现象: 
  将spring的@Component 注解的文件打包成一个jar包, test.jar. 在其他项目中无法扫描到jar包里面的类.
搜索一下是说 spring 注解是扫描 directory entries 信息. 
  执行 jar -tf test.jar 
  输出确实没有目录.

能否添加一个打包 directory entrie 的选项.

**Comment by zhyhang** [comment]
@hongdaorongThink 
此插件的原始计划导出jar，一般用法是解压到classpath下。
请帮忙提供directory entries的示例，我可以抽时间加下。
还有小小的疑问，你项目中是要经常导出jar包吗？理论上全部用maven打包就可以。

**Comment by SengerLee** [comment]
用spring annotation声明的bean，当打包在jar中时，无法被扫描到_iteyer的技术博客_51CTO博客
https://blog.51cto.com/iteyer/3239769
出现场景可以参考上面这个。

我目前也是遇到这个问题（已更新到最新版本2.3.1），有时不得不打开eclipse用来导包，很不方便，希望作者能添加一个打包 directory entrie 的选项，谢谢

**Comment by zhyhang** [comment]
@SengerLee 收到，谢谢反馈。
另外，如果sb的bean工程被其它sb工程依赖，一种方式建议，做成spring-boot-starter的autoconfiguration方式，参见官方说明：https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.developing-auto-configuration。
另外一种方式，在主工程中主应用类中增加：@ComponentScan注解。
可以试一试。
我也会抽时间，按你提供的blog方式处理一下先。

**Comment by zhyhang** [comment]
@SengerLee @hongdaorongThink Hi，已经升级，可支持add directory entries选项。plugin包已经上传，请在idea的插件市场中更新到2.4.0版本。如果有问题，请再反馈。

**Comment by SengerLee** [comment]
> @SengerLee @hongdaorongThink Hi，已经升级，可支持add目录条目选项。plugin包已经上传，请在idea的插件市场中更新到2.4.0版本。如果有问题，请再反馈。

@zhyhang 非常感谢作者及时回复信息并更新插件。我进行了更新后发现报了空指针错误，插件卸载重装后还是报同样错误，请排查一下，谢谢！

- 操作步骤：文件右键点击“Export Jar”或“Export Jar from Local Changes...”后均报此错误。
- 运行环境：IntelliJ IDEA 2022.1.1 (Ultimate Edition)，装有中文语言包插件
- 报错信息：

java.lang.NullPointerException
	at org.yanhuang.plugins.intellij.exportjar.ui.SettingDialog.initOptionCheckBox(SettingDialog.java:130)
	at org.yanhuang.plugins.intellij.exportjar.ui.SettingDialog.<init>(SettingDialog.java:100)
	at org.yanhuang.plugins.intellij.exportjar.ui.UIFactory.createSettingDialog(UIFactory.java:51)
	at org.yanhuang.plugins.intellij.exportjar.ui.UIFactory.createSettingDialog(UIFactory.java:30)
	at org.yanhuang.plugins.intellij.exportjar.ExportJarAction.actionPerformed(ExportJarAction.java:30)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$performAction$0(ActionMenuItem.java:289)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.performAction(ActionMenuItem.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:296)
...

**Comment by zhyhang** [comment]
> > @SengerLee @hongdaorongThink Hi，已经升级，可支持add目录条目选项。plugin包已经上传，请在idea的插件市场中更新到2.4.0版本。如果有问题，请再反馈。
> 
> @zhyhang 非常感谢作者及时回复信息并更新插件。我进行了更新后发现报了空指针错误，插件卸载重装后还是报同样错误，请排查一下，谢谢！
> 
> * 操作步骤：文件右键点击“Export Jar”或“Export Jar from Local Changes...”后均报此错误。
> * 运行环境：IntelliJ IDEA 2022.1.1 (Ultimate Edition)，装有中文语言包插件
> * 报错信息：
> 
> java.lang.NullPointerException at org.yanhuang.plugins.intellij.exportjar.ui.SettingDialog.initOptionCheckBox(SettingDialog.java:130) at org.yanhuang.plugins.intellij.exportjar.ui.SettingDialog.(SettingDialog.java:100) at org.yanhuang.plugins.intellij.exportjar.ui.UIFactory.createSettingDialog(UIFactory.java:51) at org.yanhuang.plugins.intellij.exportjar.ui.UIFactory.createSettingDialog(UIFactory.java:30) at org.yanhuang.plugins.intellij.exportjar.ExportJarAction.actionPerformed(ExportJarAction.java:30) at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:235) at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256) at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:235) at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$performAction$0(ActionMenuItem.java:289) at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:233) at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.performAction(ActionMenuItem.java:281) at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:296) ...

@SengerLee Hi，空指针问题已经修改。原因应该是user第一次安装使用。plugin包已经上传市场，待审核通过后，更新到2.4.1版本。谢谢反馈。发现问题再沟通。

**Comment by SengerLee** [comment]
更新了2.4.1版本后，空指针问题没有了，选中“add directory entries”生成jar文件中也包含了目录，完全满足了日常使用，非常感谢作者~！
